fix OpenMP syntax error (or compiler issue)
This is the same fix that was required for IBM XLC...

reduce.c:256:20: error: '#pragma omp barrier' cannot be immediate
substatement
       #pragma omp barrier