fix issue with missing class on Ubuntu
error: Compile server encountered fatal condition: javax/tools/DiagnosticListener java.lang.ClassNotFoundException: javax.tools.DiagnosticListener

https://stackoverflow.com/a/58253778

Signed-off-by: Jeff Hammond <jeff.science@gmail.com>